# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/livablecity/qgroundcontrol;/home/livablecity/qgroundcontrol")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.27/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "QGroundControl built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "#;~$;/\\.git;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/BUILD;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/man/(.*\\.pod|makeusage\\.sh|dummy\\..*)$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/cmake/maintainer-.*\\.cmake$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(develop|cgi-bin|.*\\.cache)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(data-distrib|data-installer)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(archive|scratch|mpfr_mpir_x86_x64_msvc2010)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/.*\\.(zip|tar\\.gz|bak|lsp)$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(autogen|biblio)\\.sh$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(makefile-admin|HOWTO-RELEASE.txt)$")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/livablecity/qgroundcontrol;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/livablecity/qgroundcontrol/AppDir/usr")
set(CPACK_MODULE_PATH "/home/livablecity/qgroundcontrol/cmake;/home/livablecity/qgroundcontrol/cmake/modules;/home/livablecity/qgroundcontrol/cmake/find-modules;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6/3rdparty/kwin;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/livablecity/Qt/6.8.3/gcc_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "GeographicLib-2.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "GeographicLib-2.5")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/livablecity/qgroundcontrol/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "karney@alum.mit.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.27/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GeographicLib library, utilities, and documentation")
set(CPACK_PACKAGE_FILE_NAME "GeographicLib-2.5")
set(CPACK_PACKAGE_HOMEPAGE_URL "qgroundcontrol.com")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GeographicLib-2.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GeographicLib-2.5")
set(CPACK_PACKAGE_NAME "QGroundControl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "GeographicLib")
set(CPACK_PACKAGE_VERSION "2.5")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.27/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.27/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "#;~$;/\\.git;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/BUILD;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/man/(.*\\.pod|makeusage\\.sh|dummy\\..*)$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/cmake/maintainer-.*\\.cmake$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(develop|cgi-bin|.*\\.cache)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(data-distrib|data-installer)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(archive|scratch|mpfr_mpir_x86_x64_msvc2010)/;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/.*\\.(zip|tar\\.gz|bak|lsp)$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(autogen|biblio)\\.sh$;/home/livablecity/qgroundcontrol/cpm_modules/geographiclib/d809160d4e1d754c2744bf0cf2ebed88d71478b0/(makefile-admin|HOWTO-RELEASE.txt)$")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/livablecity/qgroundcontrol;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/livablecity/qgroundcontrol/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "GeographicLib-2.5")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/livablecity/qgroundcontrol/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
